project:
  type: website

website:
  title: "DataSkills1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar: 
  - contents: 
    - Lab-1.qmd
    - Lab-2.qmd
    - Lab-3.qmd
    - Lab-4.qmd
    - Lab-5.qmd
    - Lab-6.qmd
    - Lab-7.qmd
    - Lab-8.qmd
    - Lab-9.qmd
    - Lab-10.qmd
    - Lab-11.qmd
    - Lab-12.qmd
    - Review-Sheet.qmd
    - Review_Sheet_2.qmd
    - Final-Review.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

# Set default options for every webpage that may or may not include webR.
webr: 
  show-startup-message: false    # Display status of webR initialization
#  show-header-message: false     # Check to see if COOP&COEP headers are set for speed.
#  packages: ['ggplot2', 'dplyr'] # Pre-install dependencies
#  base-url: ''                   # Base URL used for specifying where R WebAssembly binaries should be located
#  home-dir: '/home/rstudio'      # Customize where the working directory is
#  channel-type: 'post-message'   # Specify communication channel
#  service-worker-url: ''         # URL from where to load JavaScript worker scripts when loading webR with the ServiceWorker communication channel.

# Attach webR to every page
filters:
  - webr

